### ISSUE TITLE
limit parameter not working as expected

### ISSUE THREAD

**Issue by rinkygupta2008** [holmari/gerritstats#6]
Hi,

Limit parameter is not working as expected. whether will give --limit 10 OR --limit 1, in all cases , Its downloading last 500 commits gerrit data of Project. Please let me know , If below command is incorrect .

./gerrit_downloader.sh --server MyServerName --project MyProjectName --limit 10 --output-dir MyOutput/

**Comment by holmari** [comment]
This is a known issue; see GerritStatsReader.java:143 for the description.

There is no use in limiting the downloads to last 10 commits. The server will anyway send whatever is set in its limit (e.g. 500), and once you have the data, the tool would just have to remove the delta to your desired limit. But as the data has already been downloaded, why would you want to have less data than was downloaded?

In your particular case, no useful statistics can be calculated by downloading data for just ten commits.

The limit is useful as a ballpark setting, but it will only provide you with exact amount of data downloaded if you happen to set it to a multiple of the server limit.

I'm anyway leaving this open since to either modify the command-line interface where the behavior should be documented in some way.

**Comment by holmari** [comment]
I changed the documentation to better reflect what this flag does.
