### ISSUE TITLE
How Gerrit stats connects on Gerrit Server and what kinds of permission the gerrit server must provide

### ISSUE THREAD

**Issue by DenisBarbosa123** [holmari/gerritstats#64]
Hello guys, 

My question is how Gerrit stats connects on gerrit server, and what kinds of permission the gerrit server must provide in order to gerrit stats works fine. I don't start to use this tools yet, because I would like to get these informations in order to confirm whether my server is able to provide the data that gerrit stats needs.

Thank you!

**Comment by holmari** [comment]
The tool comprises of two parts - a downloader and a processor. The downloader, pulls in files through SSH: see https://github.com/holmari/gerritstats/blob/master/GerritDownloader/src/main/java/com/holmsted/gerrit/downloaders/ssh/SshDownloader.java for details.

There is a REST API that Gerrit provides as well, which would not require SSH. However, that's not supported by this tool. As far as I remember, it's non-trivial to add support for it since the output format is slightly different from what this tool currently expects.

Sorry for the lack of maintenance but I can't provide more support as I have not used Gerrit in my current job, for the last 4 years.
